// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/features" | "/faq" | "/news" | "/contact" | "/about";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/features": typeof import("./app/routes/features.tsx");
  "routes/faq": typeof import("./app/routes/faq.tsx");
  "routes/news": typeof import("./app/routes/news.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
};